// ============================================================
// JAVA BASICS LESSONS (Modules 1 - 7)
// ============================================================

export interface JavaLessonData {
  intro: string;
  keyConcepts: { term: string; definition: string; example?: string }[];
  codeExamples: { title: string; code: string; output?: string; note?: string }[];
  commonMistakes: string[];
  interviewTips: string[];
  interviewQuestions: { q: string; a: string }[];
  revisionPoints: string[];
}

export const BASICS_LESSONS: Record<string, JavaLessonData> = {
  // ── MODULE 1: Java Fundamentals ────────────────────────────
  'java-fundamentals': {
    intro: 'Java is a high-level, class-based, object-oriented programming language designed following the "Write Once, Run Anywhere" (WORA) philosophy. When you compile Java code, it does not convert to machine code directly; instead, it compiles into platform-neutral bytecode that executes inside the Java Virtual Machine (JVM).',
    keyConcepts: [
      { term: 'JDK (Java Development Kit)', definition: 'The full toolkit needed to develop Java applications. Contains compiler (javac), debugger, tools, and the JRE.', example: 'JDK = JRE + Development Tools (javac, jdb)' },
      { term: 'JRE (Java Runtime Environment)', definition: 'The environment required to run compiled Java applications. Contains the JVM plus the standard class libraries (rt.jar / modules).', example: 'JRE = JVM + Class Libraries' },
      { term: 'JVM (Java Virtual Machine)', definition: 'The abstract runtime engine that loads, verifies, and executes Java bytecode. Platform-specific implementations allow bytecode to run anywhere.', example: 'Bytecode (.class) -> JVM -> OS machine code' },
      { term: 'Bytecode', definition: 'Intermediate representation generated by javac compiler stored in .class files. It is not tied to any physical hardware.', example: 'javac Program.java -> Program.class' },
      { term: 'main() Method', definition: 'The universal entry point of any Java standalone application. Required signature: public static void main(String[] args).', example: 'public static void main(String[] args)' },
      { term: 'Packages & Imports', definition: 'Namespaces used to organize related classes and avoid naming collisions. Standard library uses java.lang, java.util, java.io.', example: 'package com.myapp.service; import java.util.List;' },
    ],
    codeExamples: [
      {
        title: 'Complete Standalone Java Program Structure',
        code: `package com.example;

// Class name must match filename: Main.java
public class Main {
    // Exact main signature required by JVM launcher
    public static void main(String[] args) {
        System.out.println("Hello Java!");
        System.out.println("Args count: " + args.length);
    }
}`,
        output: `Hello Java!
Args count: 0`,
        note: 'The public class name must strictly match the filename Main.java.'
      }
    ],
    commonMistakes: [
      'Missing or incorrect main() method signature (e.g. non-static, non-public, or missing String[] args).',
      'Class name casing mismatch with filename on case-sensitive operating systems.',
      'Running "java Main.class" instead of "java Main" on the command line.',
    ],
    interviewTips: [
      '"Why is Java not 100% object-oriented?" -> Because it retains 8 primitive data types (int, char, boolean, etc.) for performance reasons.',
      '"What is JIT (Just-In-Time) compiler?" -> Component of the JVM that compiles hot bytecode sequences into native machine code at runtime for high performance.',
    ],
    interviewQuestions: [
      { q: 'Explain the difference between JDK, JRE, and JVM.', a: 'JVM executes bytecode. JRE bundles the JVM with standard runtime libraries needed to run programs. JDK contains the JRE plus developer tools such as the javac compiler.' },
      { q: 'Why is Java called platform independent while the JVM is platform dependent?', a: 'Java bytecode runs on any OS without modification. However, each operating system requires a custom JVM built for its specific instruction set and kernel architecture.' },
    ],
    revisionPoints: [
      'JDK contains JRE; JRE contains JVM',
      'Source code (.java) -> javac -> Bytecode (.class) -> JVM execution',
      'main signature: public static void main(String[] args)',
      'Bytecode is platform-independent; JVM is platform-dependent',
    ]
  },

  // ── MODULE 2: Data Types & Variables ───────────────────────
  'java-data-types': {
    intro: 'Java is a strongly typed language where every variable must have a declared type. Java divides data types into 8 primitives (stored on stack directly with value) and reference types (objects and arrays stored on heap with references on stack).',
    keyConcepts: [
      { term: '8 Primitive Types', definition: 'byte (8-bit), short (16-bit), int (32-bit), long (64-bit), float (32-bit), double (64-bit), char (16-bit Unicode), boolean (true/false).', example: 'int age = 25; double pi = 3.14159;' },
      { term: 'Wrapper Classes', definition: 'Object representations of primitives (Byte, Short, Integer, Long, Float, Double, Character, Boolean) allowing them to be used in generic collections.', example: 'List<Integer> list = new ArrayList<>();' },
      { term: 'Autoboxing & Unboxing', definition: 'Automatic conversion by compiler between primitives and corresponding wrapper classes.', example: 'Integer x = 10; // autoboxing; int y = x; // unboxing' },
      { term: 'Type Casting', definition: 'Widening (implicit: byte->short->int->long->float->double) is safe; Narrowing (explicit: (int) 3.99 -> 3) can truncate or overflow.', example: 'double d = 9.99; int i = (int) d;' },
      { term: 'Integer Cache Trap', definition: 'JVM caches Integer objects for values between -128 and 127. Values in this range return the same object reference.', example: 'Integer a = 127, b = 127; a == b is true; 128 is false' },
    ],
    codeExamples: [
      {
        title: 'Primitives, Casting, and Integer Cache',
        code: `public class DataTypesDemo {
    public static void main(String[] args) {
        // Casting
        double d = 19.95;
        int price = (int) d; // Truncated to 19
        System.out.println("Truncated price: " + price);

        // Integer Cache Demonstration
        Integer x = 127, y = 127;
        System.out.println("127 == 127: " + (x == y)); // true (cached)

        Integer p = 128, q = 128;
        System.out.println("128 == 128: " + (p == q)); // false (new objects)
        System.out.println("128 equals 128: " + p.equals(q)); // true
    }
}`,
        output: `Truncated price: 19
127 == 127: true
128 == 128: false
128 equals 128: true`
      }
    ],
    commonMistakes: [
      'Using == instead of .equals() for wrapper objects.',
      'Unboxing null wrapper objects causing unexpected NullPointerExceptions at runtime.',
      'Forgetting "L" suffix on long literals (e.g. 50000000000L).',
    ],
    interviewTips: [
      'Always use BigDecimal for monetary/financial calculations instead of float or double due to floating-point rounding errors.',
      'Local variables in methods have no default values and must be initialized before use.',
    ],
    interviewQuestions: [
      { q: 'What is the Integer cache and what range does it cover?', a: 'To save memory, Java caches Integer objects for values from -128 to 127. Autoboxed values within this range point to the same object in memory, making == evaluate to true.' },
      { q: 'What happens during numeric overflow in Java?', a: 'Java does not throw an error on primitive overflow; it silently wraps around using two\'s complement binary arithmetic (e.g. (byte) 127 + 1 becomes -128).' },
    ],
    revisionPoints: [
      '8 primitives: byte, short, int, long, float, double, char, boolean',
      'Default values: int=0, double=0.0, boolean=false, objects=null',
      'Integer cache: -128 to 127',
      'Always compare wrappers using .equals()',
    ]
  },

  // ── MODULE 3: Operators ────────────────────────────────────
  'java-operators': {
    intro: 'Operators perform arithmetic, comparison, bitwise, and logical manipulations on variables and values. Understanding operator precedence, short-circuit evaluation, and increment/decrement nuances is essential for bug-free code.',
    keyConcepts: [
      { term: 'Arithmetic & Modulo', definition: '+, -, *, /, % (remainder). Integer division truncates towards zero.', example: '10 / 3 = 3; 10 % 3 = 1' },
      { term: 'Increment & Decrement', definition: 'Pre-increment (++i) increments and returns new value; Post-increment (i++) returns current value and then increments.', example: 'int i = 5; int a = i++; // a=5, i=6' },
      { term: 'Short-Circuit Logic', definition: '&& and || evaluate only as far as necessary. If left side of && is false, right side is never evaluated.', example: 'if (obj != null && obj.isValid())' },
      { term: 'Ternary Operator', definition: 'Concise inline if-else expression: condition ? valueIfTrue : valueIfFalse.', example: 'int max = a > b ? a : b;' },
      { term: 'instanceof Operator', definition: 'Tests whether an object reference is an instance of a specified class or interface at runtime.', example: 'if (animal instanceof Dog) { ... }' },
    ],
    codeExamples: [
      {
        title: 'Pre vs Post Increment and Short-Circuit Logic',
        code: `public class OperatorsDemo {
    public static void main(String[] args) {
        int a = 5;
        int res = a++ + ++a; // 5 + 7 = 12
        System.out.println("Result: " + res + ", a: " + a);

        // Short-circuit prevents NullPointerException
        String str = null;
        if (str != null && str.length() > 0) {
            System.out.println("Not empty");
        } else {
            System.out.println("Safely guarded against null!");
        }
    }
}`,
        output: `Result: 12, a: 7
Safely guarded against null!`
      }
    ],
    commonMistakes: [
      'Confusing bitwise & and | with logical short-circuiting && and ||.',
      'Complex increment expressions like i = i++ which evaluate counter-intuitively.',
    ],
    interviewTips: [
      'Operator precedence: postfix (++--) > prefix > multiplicative (* / %) > additive (+ -) > relational > equality (== !=) > logical (&& then ||) > ternary > assignment.',
    ],
    interviewQuestions: [
      { q: 'How does short-circuit evaluation prevent NullPointerException in Java?', a: 'In expression (obj != null && obj.method()), if obj is null, the left expression evaluates to false. Java short-circuits and skips obj.method(), avoiding a NullPointerException.' },
    ],
    revisionPoints: [
      '&& and || short-circuit; & and | do not',
      'i++ returns then increments; ++i increments then returns',
      '/ on ints truncates decimals; % yields remainder',
    ]
  },

  // ── MODULE 4: Decision Making & Branching ─────────────────
  'java-control-flow': {
    intro: 'Decision making constructs direct the program execution flow along different branches based on boolean evaluations and switch matching.',
    keyConcepts: [
      { term: 'if / else if / else', definition: 'Sequential conditional branching based strictly on boolean expressions. Definite assignment ensures local variables are initialized across all paths.' },
      { term: 'Traditional switch', definition: 'Matches byte, short, int, char, String, or enum. Requires break statements to prevent fall-through.', example: 'switch (opt) { case 1: doSomething(); break; default: break; }' },
      { term: 'Modern switch Expressions (->)', definition: 'Introduced in Java 14. Uses arrow syntax (->), eliminates accidental fall-through, allows multiple comma-separated labels, and can yield values.', example: 'String res = switch (day) { case 1, 7 -> "Weekend"; default -> "Weekday"; };' },
      { term: 'Short-Circuit Logic', definition: 'Operators && and || halt evaluation the instant the outcome is determined, protecting against null pointers or division by zero.', example: 'if (str != null && !str.isEmpty()) { ... }' },
    ],
    codeExamples: [
      {
        title: 'Decision Making with If-Else and Switch Expressions',
        code: `public class DecisionDemo {
    public static void main(String[] args) {
        int score = 85;
        String grade;
        if (score >= 90) {
            grade = "A";
        } else if (score >= 80) {
            grade = "B";
        } else {
            grade = "C";
        }
        System.out.println("Grade: " + grade);

        // Modern switch expression
        String day = "WED";
        String type = switch (day) {
            case "MON", "TUE", "WED", "THU", "FRI" -> "Weekday";
            case "SAT", "SUN" -> "Weekend";
            default -> "Invalid";
        };
        System.out.println("Day type: " + type);
    }
}`,
        output: `Grade: B\nDay type: Weekday`
      }
    ],
    commonMistakes: [
      'Omitting break in traditional switch statements causing unintentional fall-through.',
      'Placing a semicolon after if condition: if (score >= 90); terminates the branch immediately.',
    ],
    interviewTips: [
      'Java conditions must strictly evaluate to boolean; "if (1)" does not compile.',
      'Definite assignment: compiler verifies local variables are assigned across all branches before reading.',
    ],
    interviewQuestions: [
      { q: 'Why does switch expression not require break statements?', a: 'Modern switch expressions using arrow syntax (->) have no fall-through by design. Only the expression or block to the right of the matched arrow executes.' },
    ],
    revisionPoints: [
      'if conditions require strict boolean expressions',
      'Modern switch (Java 14+) uses -> to eliminate fall-through',
      'Definite assignment prevents reading uninitialized local variables',
    ]
  },

  // ── MODULE 5: Loops & Iterations ───────────────────────────
  'java-loops': {
    intro: 'Loops enable repetitive execution of code blocks. Java provides count-controlled loops (for), pre-condition loops (while), post-condition loops (do-while), enhanced collection traversal (for-each), and jump statements (break, continue, labeled jumps).',
    keyConcepts: [
      { term: 'for Loop', definition: 'Count-controlled loop with header (initialization; condition; update). Variables declared in header are scoped strictly inside the loop.' },
      { term: 'Enhanced for-each', definition: 'Indexless, forward-only traversal over arrays and collections. Read-only for primitive array elements.', example: 'for (int num : numbers) { System.out.println(num); }' },
      { term: 'while Loop', definition: 'Entry-controlled loop that tests condition before every iteration (can execute 0 times).' },
      { term: 'do-while Loop', definition: 'Exit-controlled loop that tests condition after loop body completes. Always executes at least once (>= 1 time).' },
      { term: 'break & continue', definition: 'break exits the nearest loop immediately. continue skips the remainder of the current iteration and jumps to next iteration.' },
      { term: 'Labeled Statements', definition: 'Labels enable break or continue to target specific outer nested loops cleanly without flags.', example: 'outer: for (...) { for (...) { if (done) break outer; } }' },
    ],
    codeExamples: [
      {
        title: 'Loops and Jumps in Action',
        code: `public class LoopsDemo {
    public static void main(String[] args) {
        // do-while always executes at least once
        int count = 10;
        do {
            System.out.println("Runs once even when count is: " + count);
            count++;
        } while (count < 5);

        // for-each loop
        int[] scores = {90, 85, 78};
        int sum = 0;
        for (int s : scores) {
            sum += s;
        }
        System.out.println("Sum: " + sum);
    }
}`,
        output: `Runs once even when count is: 10\nSum: 253`
      }
    ],
    commonMistakes: [
      'Missing state update in while loop causing infinite loop.',
      'Accidental semicolon after while: while (condition); creates an empty busy-wait.',
      'Assuming enhanced for-each reassignments modify the underlying array.',
    ],
    interviewTips: [
      'Labeled break allows breaking out of nested outer loops: outer: for (...) { break outer; }',
      'In a for loop, continue jumps to update expression; in while loop, continue jumps to condition.',
    ],
    interviewQuestions: [
      { q: 'What is the key difference between while and do-while loops?', a: 'while checks condition before loop body executes (0 or more times). do-while checks condition after executing body (always executes at least once).' },
      { q: 'Can you modify array elements using enhanced for-each?', a: 'No, for primitive arrays the loop variable is a copy by value. Reassigning it does not alter array contents.' },
    ],
    revisionPoints: [
      'do-while executes at least once (post-condition test)',
      'for loop counter variables are scoped exclusively inside the loop',
      'break terminates nearest loop; labeled break terminates specified outer loop',
    ]
  },

  // ── MODULE 6: Strings & String Pool ────────────────────────
  'java-strings': {
    intro: 'String is the most heavily used reference class in Java. Java Strings are immutable and cached in a special memory area called the String Constant Pool (SCP) in the heap to maximize memory efficiency and thread safety.',
    keyConcepts: [
      { term: 'Immutability', definition: 'Once created, a String instance cannot be modified. Any modification returns a new String instance.', example: 'String s = "A"; s = s + "B"; // creates new object' },
      { term: 'String Constant Pool', definition: 'A pool of unique String literals stored inside the Heap. String literals share pool references; new String("...") creates distinct heap object.', example: '"Java" == "Java" (true); "Java" == new String("Java") (false)' },
      { term: 'StringBuilder', definition: 'Mutable, non-synchronized, fast sequence of characters. Ideal for loops and single-threaded operations.', example: 'StringBuilder sb = new StringBuilder(); sb.append("x");' },
      { term: 'StringBuffer', definition: 'Mutable, thread-safe (synchronized), slower character sequence. Use only when synchronization across threads is required.', example: 'StringBuffer sbf = new StringBuffer();' },
      { term: '.equals() vs ==', definition: '== compares memory references. .equals() compares character sequence contents.', example: 's1.equals(s2)' },
    ],
    codeExamples: [
      {
        title: 'String Pool and StringBuilder Performance',
        code: `public class StringDemo {
    public static void main(String[] args) {
        String s1 = "Hello";
        String s2 = "Hello";
        String s3 = new String("Hello");

        System.out.println("s1 == s2: " + (s1 == s2)); // true (same pool object)
        System.out.println("s1 == s3: " + (s1 == s3)); // false (heap vs pool)
        System.out.println("s1.equals(s3): " + s1.equals(s3)); // true (same content)

        // StringBuilder for efficient concatenation
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i <= 3; i++) {
            sb.append(i).append(" ");
        }
        System.out.println("Builder result: " + sb.toString().trim());
    }
}`,
        output: `s1 == s2: true
s1 == s3: false
s1.equals(s3): true
Builder result: 1 2 3`
      }
    ],
    commonMistakes: [
      'Comparing String content with == instead of .equals().',
      'Using String concatenation (+) inside large loops, generating thousands of garbage objects.',
    ],
    interviewTips: [
      '"Why are Strings immutable in Java?" -> Security (used in classloading, database credentials, network connections), thread safety without synchronization, and enabling the String Constant Pool.',
    ],
    interviewQuestions: [
      { q: 'What is the difference between String, StringBuilder, and StringBuffer?', a: 'String is immutable (thread-safe, high memory overhead on changes). StringBuilder is mutable and not thread-safe (fastest for single-threaded string building). StringBuffer is mutable and thread-safe via synchronized methods (slower).' },
      { q: 'What does the intern() method do on a String?', a: 'When s.intern() is invoked, if the pool already contains a string equal to s, the pool reference is returned. If not, s is added to the pool and returned.' },
    ],
    revisionPoints: [
      'Strings are immutable and stored in the String Constant Pool',
      'Always use .equals() for content comparison',
      'Use StringBuilder for single-threaded mutation in loops',
      'String is declared final; cannot be subclassed',
    ]
  },

  // ── MODULE 6: Arrays & Algorithms ──────────────────────────
  'java-arrays': {
    intro: 'An array is a fixed-size, contiguous block of memory storing elements of the same data type. In Java, arrays are objects stored on the heap with 0-based indexing.',
    keyConcepts: [
      { term: 'Array Declaration & Allocation', definition: 'Fixed length established at creation time and accessible via the .length property (not a method).', example: 'int[] arr = new int[10]; or int[] arr = {1, 2, 3};' },
      { term: 'Contiguous Memory', definition: 'Elements stored adjacent in memory, providing O(1) random access by index.', example: 'arr[0], arr[length - 1]' },
      { term: 'Arrays Utility Class', definition: 'java.util.Arrays provides static helper methods: sort(), binarySearch(), copyOf(), equals(), toString().', example: 'Arrays.sort(arr);' },
      { term: 'Multidimensional Arrays', definition: 'Arrays of arrays in Java, allowing jagged (non-rectangular) structures.', example: 'int[][] matrix = new int[3][3];' },
    ],
    codeExamples: [
      {
        title: 'Two-Pointer Array Reversal',
        code: `import java.util.Arrays;

public class ArrayReverseDemo {
    public static void main(String[] args) {
        int[] nums = {10, 20, 30, 40, 50};

        int left = 0, right = nums.length - 1;
        while (left < right) {
            int temp = nums[left];
            nums[left] = nums[right];
            nums[right] = temp;
            left++;
            right--;
        }

        System.out.println("Reversed: " + Arrays.toString(nums));
    }
}`,
        output: 'Reversed: [50, 40, 30, 20, 10]'
      }
    ],
    commonMistakes: [
      'Using arr.length() instead of arr.length (arrays have a field, not a method).',
      'ArrayIndexOutOfBoundsException by querying index equal to array.length.',
      'Assigning one array variable to another and expecting a deep copy (it only copies reference).',
    ],
    interviewTips: [
      'Common array interview patterns: Two Pointers, Sliding Window, Prefix Sums, Binary Search (on sorted array).',
    ],
    interviewQuestions: [
      { q: 'How do you find the second largest element in an array in O(n) time?', a: 'Maintain two variables, max and secondMax. Iterate through the array once: if current > max, secondMax = max and max = current; else if current > secondMax and current != max, secondMax = current.' },
    ],
    revisionPoints: [
      'Fixed size; O(1) index lookup; O(n) search/insert',
      '.length is a property, not a method',
      'Arrays are objects stored on heap',
      'Arrays.sort() uses Dual-Pivot Quicksort for primitives O(n log n)',
    ]
  },

  // ── MODULE 7: Methods & Recursion ──────────────────────────
  'java-methods': {
    intro: 'Methods are modular blocks of reusable code associated with a class or object. A method signature consists of its name and parameter types. Java is strictly pass-by-value for all types.',
    keyConcepts: [
      { term: 'Method Signature', definition: 'Consists solely of method name and parameter types list. Return type is NOT part of signature.', example: 'void calculate(int a, double b)' },
      { term: 'Strictly Pass-by-Value', definition: 'Java ALWAYS passes parameters by value. For primitives, copies value; for objects, copies the reference memory address (not the object itself).', example: 'swap(a, b) cannot swap caller variables' },
      { term: 'Method Overloading', definition: 'Multiple methods in the SAME class sharing the same name but having DIFFERENT parameter lists. Resolved at compile time.', example: 'add(int a, int b) and add(double a, double b)' },
      { term: 'Recursion', definition: 'A method that invokes itself until reaching a base condition. Every recursive call pushes a stack frame.', example: 'int fact(n) { return n <= 1 ? 1 : n * fact(n - 1); }' },
      { term: 'varargs (Variable Arguments)', definition: 'Allows passing zero or more arguments of specified type. Must be the final parameter.', example: 'public void log(String... messages)' },
    ],
    codeExamples: [
      {
        title: 'Pass-by-Value Demonstration',
        code: `public class PassByValueDemo {
    static void modify(int num, int[] arr) {
        num = 999;       // Modifies local copy only
        arr[0] = 999;    // Modifies content of referenced object
    }

    public static void main(String[] args) {
        int x = 10;
        int[] data = {1, 2, 3};
        modify(x, data);

        System.out.println("x after modify: " + x);         // 10
        System.out.println("data[0] after modify: " + data[0]); // 999
    }
}`,
        output: `x after modify: 10
data[0] after modify: 999`
      }
    ],
    commonMistakes: [
      'Thinking Java has pass-by-reference. It does not. The reference itself is passed by value.',
      'Missing base condition in recursion leading to StackOverflowError.',
      'Overloading based solely on different return types (compile error).',
    ],
    interviewTips: [
      '"Is Java pass-by-value or pass-by-reference?" -> Always pass-by-value. You pass the value of the reference (pointer copy), so you can mutate object state, but reassigning the parameter variable inside the method has no effect on the caller.',
    ],
    interviewQuestions: [
      { q: 'Can you overload a method by changing only the return type in Java?', a: 'No. The compiler differentiates overloaded methods strictly by their parameter list (number, types, and order). Changing only the return type causes a compilation error.' },
    ],
    revisionPoints: [
      'Java is strictly pass-by-value for all variables',
      'Overloading = same name, different parameters (compile time)',
      'Recursion requires a base case to avoid StackOverflowError',
      'varargs must always be the last parameter',
    ]
  },
};
