// ============================================================
// LIGHTWEIGHT SUBLESSON MANIFEST (OPTIMIZED FOR FAST ROADMAP LOADS)
// Automatically generated: 133 sublessons
// ============================================================

import { SubLessonSummary } from '@/types';

export const SUBLESSON_MANIFEST: SubLessonSummary[] = [
  {
    "id": "what-is-java",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.1",
    "title": "What is Java & Why Java?",
    "subtitle": "History, key design goals, the Write Once, Run Anywhere (WORA) philosophy, and enterprise architecture",
    "estimatedMinutes": 10,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "jdk-jre-jvm",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.2",
    "title": "JDK vs JRE vs JVM Architecture",
    "subtitle": "The 3 execution tiers: developer tools, runtime libraries, execution engine, and classloader subsystems",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "bytecode-compilation",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.3",
    "title": "Bytecode & Compilation Process",
    "subtitle": "The javac compiler pipeline, .class file layout, magic number 0xCAFEBABE, and HotSpot JIT tiered compilation",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "main-method-breakdown",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.4",
    "title": "The main() Method Line-by-Line",
    "subtitle": "public static void main(String[] args) keyword breakdown, JVM bootstrap, command-line arguments, and exit codes",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "packages-and-imports",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.5",
    "title": "Packages & Imports",
    "subtitle": "Namespaces, reverse domain naming, single vs wildcard imports, static imports, and package-private visibility",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "classpath-and-execution",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.6",
    "title": "Classpath & Execution",
    "subtitle": "Classpath mechanics (-cp), JAR execution, Manifest files, ClassNotFoundException vs NoClassDefFoundError",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "fundamentals-challenge",
    "moduleId": "java-fundamentals",
    "moduleTitle": "1. Java Fundamentals",
    "lessonNumber": "Lesson 1.7",
    "title": "Module 1 Challenge & Interview Assessment",
    "subtitle": "Comprehensive capstone assessment synthesizing JDK/JRE/JVM architecture, classloader delegation, bytecode inspection, packages, and classpath execution",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "variables-and-scope",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.1",
    "title": "Variables, Declaration & Scope",
    "subtitle": "Declaration vs initialization, stack frame lifecycle, local vs instance vs static scope, and uninitialized variable errors",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "primitive-types-deep-dive",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.2",
    "title": "The 8 Primitive Data Types",
    "subtitle": "Memory footprints, value ranges, two's complement binary representation, and precision boundaries",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "type-casting-and-overflow",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.3",
    "title": "Type Casting & Numeric Overflow",
    "subtitle": "Widening vs narrowing conversions, bit truncation, circular overflow wrapping, and safe math with Math.exact methods",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "wrapper-classes",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.4",
    "title": "Wrapper Classes",
    "subtitle": "Object encapsulation of primitives, type utility methods, parsing vs valueOf, immutability, and heap overhead",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "autoboxing-and-unboxing",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.5",
    "title": "Autoboxing & Unboxing",
    "subtitle": "Syntactic sugar mechanics, compiler bytecodes (valueOf vs intValue), silent performance degradation, and unboxing NullPointerException",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "integer-cache-trap",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.6",
    "title": "The Integer Cache Trap (-128 to 127)",
    "subtitle": "Flyweight caching pattern, JLS §5.1.7 specifications, -XX:AutoBoxCacheMax tuning, and reference vs value equality bugs",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "floating-point-bigdecimal",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.7",
    "title": "Floating-Point Precision & BigDecimal",
    "subtitle": "IEEE 754 representation, recurring binary fractions (0.1 + 0.2 != 0.3), arbitrary-precision math, constructor traps, and scale management",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "data-types-challenge",
    "moduleId": "java-data-types",
    "moduleTitle": "2. Data Types & Variables",
    "lessonNumber": "Lesson 2.8",
    "title": "Module 2 Challenge & Interview Assessment",
    "subtitle": "Comprehensive capstone assessment synthesizing primitives, IEEE 754, type casting wrap-around, wrapper immutability, IntegerCache traps, and BigDecimal",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "arithmetic-and-modulo",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.1",
    "title": "Arithmetic Operators & Modulo (%)",
    "subtitle": "Integer division, floating-point math, operator precedence, and the power of the remainder operator",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "pre-post-increment",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.2",
    "title": "Pre vs Post Increment (++i vs i++)",
    "subtitle": "Prefix vs postfix evaluation order, expression values, and memory mutation mechanics",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "relational-equality",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.3",
    "title": "Relational & Equality Operators (== vs .equals())",
    "subtitle": "Comparing primitives, boolean evaluation, and the essential difference between == and .equals()",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "short-circuit-evaluation",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.4",
    "title": "Logical Operators & Short-Circuiting",
    "subtitle": "Short-circuit evaluation (&&, ||), logical NOT (!), side-effect traps, and guarding against runtime errors",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "assignment-operators",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.5",
    "title": "Assignment Operators & The Compound Cast Trap",
    "subtitle": "Simple assignment, compound assignment operators, evaluation order, and hidden implicit casting",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "ternary-operator",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.6",
    "title": "The Ternary Operator (? :)",
    "subtitle": "Inline conditional expressions, type unification, auto-unboxing NPEs, and evaluation short-circuiting",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "bitwise-shift-operators",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.7",
    "title": "Bitwise & Shift Operators",
    "subtitle": "Manipulating individual binary bits (&, |, ^, ~, <<, >>, >>>)",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "instanceof-operator",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.8",
    "title": "The instanceof Operator & Pattern Matching",
    "subtitle": "Checking object runtime types safely and Java 14+ pattern matching",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "operator-precedence",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.9",
    "title": "Operator Precedence & Associativity",
    "subtitle": "Which operator runs first? Parentheses as the golden rule for clarity",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "operators-challenge",
    "moduleId": "java-operators",
    "moduleTitle": "3. Operators & Expressions",
    "lessonNumber": "Lesson 3.10",
    "title": "Module 3 Challenge & Interview Assessment",
    "subtitle": "Comprehensive technical assessment: increment/decrement side-effects, short-circuit evaluation, compound cast traps, ternary unboxing NPEs, bitmasks, pattern matching instanceof, and operator precedence",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "if-else-ladder",
    "moduleId": "java-control-flow",
    "moduleTitle": "4. Decision Making & Branching",
    "lessonNumber": "Lesson 4.1",
    "title": "If-Else Ladders & Decision Making",
    "subtitle": "Branching execution paths, strict boolean conditions, short-circuit logic, and definite assignment",
    "estimatedMinutes": 14,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "switch-statement",
    "moduleId": "java-control-flow",
    "moduleTitle": "4. Decision Making & Branching",
    "lessonNumber": "Lesson 4.2",
    "title": "The Traditional Switch Statement & Fall-Through",
    "subtitle": "Multi-way jump tables, supported selector types, intentional vs accidental fall-through, and block scoping",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "switch-expressions",
    "moduleId": "java-control-flow",
    "moduleTitle": "4. Decision Making & Branching",
    "lessonNumber": "Lesson 4.3",
    "title": "Modern Switch Expressions (->)",
    "subtitle": "Arrow syntax, producing values, exhaustiveness enforcement, multi-label matching, and the yield keyword",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "control-flow-challenge",
    "moduleId": "java-control-flow",
    "moduleTitle": "4. Decision Making & Branching",
    "lessonNumber": "Lesson 4.4",
    "title": "Module 4 Challenge & Interview Assessment",
    "subtitle": "Branching execution paths, strict boolean conditions, switch fall-through, switch expressions (->), yield keyword, and definite assignment",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "for-loop-deep-dive",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.1",
    "title": "The For Loop Deep Dive",
    "subtitle": "Mastering the three-part loop header, execution cycle, multi-variable declarations, scoping rules, and complexity patterns",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "enhanced-for-each",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.2",
    "title": "The Enhanced For-Each Loop",
    "subtitle": "Simplified array traversal, read-only iteration semantics, indexless processing, and performance",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "while-loop",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.3",
    "title": "The While Loop (Pre-Condition Loop)",
    "subtitle": "Entry-controlled repetition, indefinite iterations, state evolution, and avoiding infinite loops",
    "estimatedMinutes": 12,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "do-while-loop",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.4",
    "title": "The do-while Loop (Runs >= 1 Time)",
    "subtitle": "Post-condition evaluation, the mandatory semicolon, variable scope boundaries, and interactive validation loops",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "break-continue-labeled",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.5",
    "title": "Break, Continue & Labeled Statements",
    "subtitle": "Early loop termination, skipping iterations, labeled multi-level jumps, and unreachable code traps",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "nested-loops-and-tracing",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.6",
    "title": "Nested Loops & Loop Tracing",
    "subtitle": "Multi-dimensional iterations, coordinate grids, total iteration calculations, and systematic execution tracing",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "loops-challenge",
    "moduleId": "java-loops",
    "moduleTitle": "5. Loops & Iterations",
    "lessonNumber": "Lesson 5.7",
    "title": "Module 5 Challenge & Interview Assessment",
    "subtitle": "Loop invariants, off-by-one boundary conditions, enhanced for-each bytecode mechanics, while vs do-while post-condition guarantees, labeled breaks, and nested loop tracing",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "star-patterns-and-pyramids",
    "moduleId": "java-patterns",
    "moduleTitle": "6. Pattern Programs & Logic Building",
    "lessonNumber": "Lesson 6.1",
    "title": "Star Patterns & Symmetrical Pyramids",
    "subtitle": "Nested loop coordinate mapping (row i, column j), spaces vs star mathematical relations, right-angled triangles, inverted pyramids, centered pyramids, diamonds, hollow diamonds, and butterfly patterns",
    "estimatedMinutes": 35,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "number-patterns-and-series",
    "moduleId": "java-patterns",
    "moduleTitle": "6. Pattern Programs & Logic Building",
    "lessonNumber": "Lesson 6.2",
    "title": "Number Patterns, Floyds & Pascal Triangle",
    "subtitle": "Linear incrementing sequences, Floyd triangle, binary 0-1 alternating triangles, Pascal triangle formula nCr, palindromic number pyramids, and number spirals",
    "estimatedMinutes": 35,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "character-alphabet-patterns",
    "moduleId": "java-patterns",
    "moduleTitle": "6. Pattern Programs & Logic Building",
    "lessonNumber": "Lesson 6.3",
    "title": "Character & Alphabet Pattern Logic",
    "subtitle": "ASCII / Unicode char arithmetic (char c = (char)('A' + j)), contiguous alphabetic triangles, palindromic character pyramids, hollow character diamonds, and cyclical character grids",
    "estimatedMinutes": 35,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "advanced-matrix-spiral-patterns",
    "moduleId": "java-patterns",
    "moduleTitle": "6. Pattern Programs & Logic Building",
    "lessonNumber": "Lesson 6.4",
    "title": "Advanced Matrix & Inward Spiral Patterns",
    "subtitle": "4-boundary shrinking box algorithm (top, bottom, left, right), concentric number square grids, zigzag snake matrix traversal, diagonal printing, and matrix rotation",
    "estimatedMinutes": 40,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "patterns-challenge",
    "moduleId": "java-patterns",
    "moduleTitle": "6. Pattern Programs & Logic Building",
    "lessonNumber": "Lesson 6.5",
    "title": "Module 6 Challenge & Interview Assessment",
    "subtitle": "Coordinate geometry transformations, boundary condition mathematical proofs, concentric spiral algorithms, space-time optimization, and logic building interview mastery",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "method-anatomy-and-returns",
    "moduleId": "java-methods",
    "moduleTitle": "7. Methods in Java",
    "lessonNumber": "Lesson 7.1",
    "title": "Method Anatomy, Parameters & Return Types",
    "subtitle": "Deconstructing method declarations, formal parameters vs actual arguments, execution boundaries, and stack frame lifecycle",
    "estimatedMinutes": 16,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "pass-by-value-deep-dive",
    "moduleId": "java-methods",
    "moduleTitle": "7. Methods in Java",
    "lessonNumber": "Lesson 7.2",
    "title": "Pass-by-Value Semantics in Java",
    "subtitle": "Stack frame value copying, reference bit-patterns, heap mutation vs reference reassignment, and why Java has no pass-by-reference",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "method-overloading-and-varargs",
    "moduleId": "java-methods",
    "moduleTitle": "7. Methods in Java",
    "lessonNumber": "Lesson 7.3",
    "title": "Method Overloading & Varargs",
    "subtitle": "Static compile-time polymorphism, signature differentiation, the overload resolution waterfall, and variable-length argument mechanics",
    "estimatedMinutes": 17,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "methods-challenge",
    "moduleId": "java-methods",
    "moduleTitle": "7. Methods in Java",
    "lessonNumber": "Lesson 7.4",
    "title": "Module 7 Challenge & Interview Assessment",
    "subtitle": "Strict pass-by-value semantics, stack frame execution boundaries, method signature contracts, ambiguous overloading resolution, varargs bytecode mechanics, and recursion base cases",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "array-declaration-and-memory",
    "moduleId": "java-arrays",
    "moduleTitle": "8. Arrays & 2D Matrix",
    "lessonNumber": "Lesson 8.1",
    "title": "Array Declaration, Memory Allocation & Indexing",
    "subtitle": "Stack reference vs Heap objects, fixed length, zero-based indexing, and default initialization values",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 11
  },
  {
    "id": "array-traversals-and-algorithms",
    "moduleId": "java-arrays",
    "moduleTitle": "8. Arrays & 2D Matrix",
    "lessonNumber": "Lesson 8.2",
    "title": "Array Traversals & Common Patterns",
    "subtitle": "Standard for loops, enhanced for-each loop, two-pointer reversal, linear search, and running statistics",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 11
  },
  {
    "id": "arrays-utility-class",
    "moduleId": "java-arrays",
    "moduleTitle": "8. Arrays & 2D Matrix",
    "lessonNumber": "Lesson 8.3",
    "title": "The java.util.Arrays Utility Class",
    "subtitle": "Deep printing with toString(), Dual-Pivot Quicksort with sort(), logarithmic binarySearch(), fill(), and copyOf()",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "two-dimensional-arrays-and-matrices",
    "moduleId": "java-arrays",
    "moduleTitle": "8. Arrays & 2D Matrix",
    "lessonNumber": "Lesson 8.4",
    "title": "2D Arrays & Matrix Traversal",
    "subtitle": "Arrays of arrays, row-major vs column-major traversal, jagged (ragged) arrays, and matrix operations",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "arrays-challenge",
    "moduleId": "java-arrays",
    "moduleTitle": "8. Arrays & 2D Matrix",
    "lessonNumber": "Lesson 8.5",
    "title": "Module 8 Challenge & Interview Assessment",
    "subtitle": "Array heap layout, cache locality, shallow vs deep copying, array covariance ArrayStoreException, jagged matrices, in-place matrix operations, and java.util.Arrays algorithms",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "string-immutability-and-memory",
    "moduleId": "java-strings",
    "moduleTitle": "9. Strings & String Pool",
    "lessonNumber": "Lesson 9.1",
    "title": "String Immutability & Memory Internals",
    "subtitle": "The String Constant Pool (SCP), heap mechanics, value immutability, literal vs new String(), and intern()",
    "estimatedMinutes": 16,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "string-equality-and-comparisons",
    "moduleId": "java-strings",
    "moduleTitle": "9. Strings & String Pool",
    "lessonNumber": "Lesson 9.2",
    "title": "String Equality: == vs .equals() & SCP",
    "subtitle": "Reference identity vs value equality, equalsIgnoreCase(), compareTo(), compile-time constants, and the intern() mechanism",
    "estimatedMinutes": 15,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "string-methods-and-manipulation",
    "moduleId": "java-strings",
    "moduleTitle": "9. Strings & String Pool",
    "lessonNumber": "Lesson 9.3",
    "title": "Essential String Methods & Manipulation",
    "subtitle": "Inspection, extraction, searching, transforming, trimming, splitting, and character traversal",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "stringbuilder-vs-stringbuffer",
    "moduleId": "java-strings",
    "moduleTitle": "9. Strings & String Pool",
    "lessonNumber": "Lesson 9.4",
    "title": "StringBuilder vs StringBuffer & Performance",
    "subtitle": "Mutable text buffers, capacity management, method chaining, thread safety, and benchmark mechanics",
    "estimatedMinutes": 16,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "strings-challenge",
    "moduleId": "java-strings",
    "moduleTitle": "9. Strings & String Pool",
    "lessonNumber": "Lesson 9.5",
    "title": "Module 9 Challenge & Interview Assessment",
    "subtitle": "String immutability, String Constant Pool (SCP) native hashtable, Compact Strings (byte[] + coder), intern() mechanics, StringConcatFactory invokedynamic, and StringBuilder vs StringBuffer",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "recursion-and-call-stack",
    "moduleId": "java-recursion",
    "moduleTitle": "10. Recursion & Call Stack",
    "lessonNumber": "Lesson 10.1",
    "title": "Recursion Fundamentals & Call Stack Tracing",
    "subtitle": "Recursive problem decomposition, base cases, winding vs unwinding phases, the call stack memory model, and recursion tree analysis",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "recursion-head-tail-tree",
    "moduleId": "java-recursion",
    "moduleTitle": "10. Recursion & Call Stack",
    "lessonNumber": "Lesson 10.2",
    "title": "Head vs Tail Recursion & Memory Optimization",
    "subtitle": "Head recursion vs tail recursion mechanics, accumulator parameter passing, why JVM HotSpot does not optimize tail calls (TCO), and tree recursion complexity",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "recursion-arrays-and-strings",
    "moduleId": "java-recursion",
    "moduleTitle": "10. Recursion & Call Stack",
    "lessonNumber": "Lesson 10.3",
    "title": "Recursion on Arrays & Divide-and-Conquer",
    "subtitle": "Array index navigation, binary search recursion, string reversal and palindromes, divide-and-conquer recurrence relations, and call stack bounds",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "recursion-backtracking-foundations",
    "moduleId": "java-recursion",
    "moduleTitle": "10. Recursion & Call Stack",
    "lessonNumber": "Lesson 10.4",
    "title": "Backtracking Foundations & State Restoration",
    "subtitle": "The Choose-Explore-Unchoose paradigm, state space tree traversal, subset generation, permutations, pruning dead branches, and preventing stack overflow",
    "estimatedMinutes": 30,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "recursion-challenge",
    "moduleId": "java-recursion",
    "moduleTitle": "10. Recursion & Call Stack",
    "lessonNumber": "Lesson 10.5",
    "title": "Module 10 Challenge & Technical Interview Assessment",
    "subtitle": "Comprehensive assessment covering call stack memory dynamics, recursion depth limits (-Xss), base case invariants, tail call optimization realities, memoization vs tabulation, and backtracking tree exploration",
    "estimatedMinutes": 25,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "why-oop-fundamentals",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.1",
    "title": "Why OOP? (Procedural vs Object-Oriented Programming)",
    "subtitle": "Understanding the limitations of procedural programming and the four fundamental pillars of the Object-Oriented paradigm",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "what-is-a-class",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.2",
    "title": "What is a Class? (Class Structure & Member Variables)",
    "subtitle": "Understanding class anatomy, member variables (state), member methods (behavior), and access levels in Java",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "creating-objects-with-new",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.3",
    "title": "Creating Objects with the 'new' Keyword",
    "subtitle": "Object instantiation on the Heap, the dot operator (member access), dynamic allocation, and independent instance state",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "references-and-memory",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.4",
    "title": "Object References & Memory (Stack vs Heap, Aliasing & Null)",
    "subtitle": "JVM Stack memory vs Heap memory, reference pointer mechanics, aliasing, and default initialization",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "constructors-initialization",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.5",
    "title": "Constructors in Java (Default vs Parameterized & Overloading)",
    "subtitle": "Constructor syntax, default vs no-arg vs parameterized constructors, constructor overloading, and initialization guarantees",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "this-keyword-and-chaining",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.6",
    "title": "The 'this' Keyword & Constructor Chaining (this())",
    "subtitle": "Current object reference, resolving variable shadowing, constructor chaining with this(), and rules of invocation",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "static-vs-instance",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.7",
    "title": "Static Variables & Methods vs Instance Members",
    "subtitle": "Class-level memory allocation in Metaspace, shared state across instances, static method constraints, and static initializers",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "object-lifecycle-and-gc",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.8",
    "title": "Object Lifecycle & Garbage Collection in Java",
    "subtitle": "Object lifecycle stages, unreachability mechanisms, JVM Garbage Collection roots, mark-and-sweep, and finalize() deprecation",
    "estimatedMinutes": 8,
    "exerciseCount": 3,
    "quizCount": 10,
    "interviewCount": 8
  },
  {
    "id": "oop-fundamentals-challenge",
    "moduleId": "java-oop-basics",
    "moduleTitle": "1. OOP Fundamentals",
    "lessonNumber": "Lesson 1.9",
    "title": "Module 1 Challenge & Interview Assessment",
    "subtitle": "Comprehensive assessment, real-world interview challenges, and capstone coding exercises combining all OOP fundamentals",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "encapsulation-principles",
    "moduleId": "java-encapsulation",
    "moduleTitle": "2. Encapsulation & Data Hiding",
    "lessonNumber": "Lesson 2.1",
    "title": "The Principle of Encapsulation & Data Hiding",
    "subtitle": "Bundling data with behavior, restricting direct state manipulation, maintaining class invariants, and reducing architectural coupling",
    "estimatedMinutes": 18,
    "exerciseCount": 3,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "access-modifiers-deep-dive",
    "moduleId": "java-encapsulation",
    "moduleTitle": "2. Encapsulation & Data Hiding",
    "lessonNumber": "Lesson 2.2",
    "title": "Java's 4 Access Modifiers",
    "subtitle": "Private, package-private (default), protected, and public scopes across classes, packages, and compilation units",
    "estimatedMinutes": 18,
    "exerciseCount": 3,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "getters-setters-defensive-copying",
    "moduleId": "java-encapsulation",
    "moduleTitle": "2. Encapsulation & Data Hiding",
    "lessonNumber": "Lesson 2.3",
    "title": "Getters, Setters & Defensive Copying",
    "subtitle": "JavaBeans conventions, validation guards, and preventing internal representation leaks with mutable reference types",
    "estimatedMinutes": 18,
    "exerciseCount": 3,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "immutable-class-pattern",
    "moduleId": "java-encapsulation",
    "moduleTitle": "2. Encapsulation & Data Hiding",
    "lessonNumber": "Lesson 2.4",
    "title": "Immutable Class Design Pattern",
    "subtitle": "Thread-safe, side-effect-free architecture using private final fields, defensive copying, and functional 'with-er' methods",
    "estimatedMinutes": 18,
    "exerciseCount": 3,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "encapsulation-challenge",
    "moduleId": "java-encapsulation",
    "moduleTitle": "2. Encapsulation & Data Hiding",
    "lessonNumber": "Lesson 2.5",
    "title": "Module 2 Challenge & Interview Assessment",
    "subtitle": "Comprehensive assessment, real-world interview challenges, and capstone coding exercises combining all encapsulation pillars",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "what-is-inheritance",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.1",
    "title": "What is Inheritance? (The extends Keyword & IS-A)",
    "subtitle": "Stop repeating code: How child classes get methods and variables from parent classes",
    "estimatedMinutes": 20,
    "exerciseCount": 7,
    "quizCount": 5,
    "interviewCount": 3
  },
  {
    "id": "types-of-inheritance",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.2",
    "title": "Types of Inheritance in Java (And Why Multiple Inheritance is Not Allowed)",
    "subtitle": "Single, Multilevel, and Hierarchical inheritance, plus the Diamond Problem explained simply",
    "estimatedMinutes": 20,
    "exerciseCount": 7,
    "quizCount": 4,
    "interviewCount": 3
  },
  {
    "id": "super-constructor-chaining",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.3",
    "title": "Constructors & super() in Inheritance",
    "subtitle": "How parent constructors run first, and how child classes pass data to parents",
    "estimatedMinutes": 22,
    "exerciseCount": 7,
    "quizCount": 3,
    "interviewCount": 3
  },
  {
    "id": "method-overriding-rules",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.4",
    "title": "Method Overriding & The @Override Annotation",
    "subtitle": "Giving child classes their own special behavior when parent behavior is too general",
    "estimatedMinutes": 22,
    "exerciseCount": 7,
    "quizCount": 3,
    "interviewCount": 3
  },
  {
    "id": "super-method-and-variable",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.5",
    "title": "Calling Parent Methods & Variables: super.method() and super.var",
    "subtitle": "How to reuse parent code without throwing it away, and the complete this vs super breakdown",
    "estimatedMinutes": 20,
    "exerciseCount": 7,
    "quizCount": 3,
    "interviewCount": 3
  },
  {
    "id": "final-keyword-in-oop",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.6",
    "title": "The final Keyword in Inheritance: Locking Classes & Methods",
    "subtitle": "Protecting your classes from being extended and methods from being changed",
    "estimatedMinutes": 20,
    "exerciseCount": 7,
    "quizCount": 3,
    "interviewCount": 3
  },
  {
    "id": "inheritance-challenge",
    "moduleId": "java-inheritance",
    "moduleTitle": "3. Inheritance & Hierarchy",
    "lessonNumber": "Lesson 3.7",
    "title": "Inheritance Mastery: 10 Challenges & Interview Cheatsheet",
    "subtitle": "Test your skills from beginner to interview-ready with 10 progressive coding challenges, 15 MCQs, 10 tricky puzzles, and revision cheatsheet",
    "estimatedMinutes": 35,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 10
  },
  {
    "id": "compile-vs-runtime-polymorphism",
    "moduleId": "java-polymorphism",
    "moduleTitle": "4. Polymorphism & Dispatch",
    "lessonNumber": "Lesson 4.1",
    "title": "Compile-Time vs Runtime Polymorphism",
    "subtitle": "Static binding vs dynamic dispatch, method overloading vs method overriding, and bytecode invocation opcodes",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 20,
    "interviewCount": 10
  },
  {
    "id": "dynamic-method-dispatch",
    "moduleId": "java-polymorphism",
    "moduleTitle": "4. Polymorphism & Dispatch",
    "lessonNumber": "Lesson 4.2",
    "title": "Dynamic Method Dispatch & Virtual Method Invocation",
    "subtitle": "How the JVM invokes methods at runtime: the vtable (virtual method table), invokevirtual bytecode, and object headers",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 20,
    "interviewCount": 10
  },
  {
    "id": "casting-and-classcastexception",
    "moduleId": "java-polymorphism",
    "moduleTitle": "4. Polymorphism & Dispatch",
    "lessonNumber": "Lesson 4.3",
    "title": "Upcasting, Downcasting & ClassCastException",
    "subtitle": "Widening reference conversion vs narrowing reference conversion, heap object safety, and handling ClassCastException",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 20,
    "interviewCount": 10
  },
  {
    "id": "instanceof-and-pattern-matching",
    "moduleId": "java-polymorphism",
    "moduleTitle": "4. Polymorphism & Dispatch",
    "lessonNumber": "Lesson 4.4",
    "title": "The instanceof Operator & Modern Pattern Matching",
    "subtitle": "Runtime type testing, null safety, modern Java pattern matching syntax, and scoping rules",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 20,
    "interviewCount": 10
  },
  {
    "id": "polymorphism-challenge",
    "moduleId": "java-polymorphism",
    "moduleTitle": "4. Polymorphism & Dispatch",
    "lessonNumber": "Lesson 4.5",
    "title": "Module 4 Challenge & Interview Assessment",
    "subtitle": "Comprehensive assessment, real-world interview challenges, and capstone coding exercises combining all polymorphism pillars",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "abstract-classes-and-methods",
    "moduleId": "java-abstraction",
    "moduleTitle": "5. Abstraction & Interfaces",
    "lessonNumber": "Lesson 5.1",
    "title": "Abstract Classes & Abstract Methods",
    "subtitle": "Incomplete blueprints, mandatory sub-class overrides, partial implementation, and constructor execution in abstract hierarchies",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "interfaces-and-contracts",
    "moduleId": "java-abstraction",
    "moduleTitle": "5. Abstraction & Interfaces",
    "lessonNumber": "Lesson 5.2",
    "title": "Interfaces: Contracts & Multiple Inheritance of Type",
    "subtitle": "Pure behavioral capability contracts, constant fields (public static final), implementing multiple interfaces, and polymorphic abstraction",
    "estimatedMinutes": 22,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "abstract-class-vs-interface",
    "moduleId": "java-abstraction",
    "moduleTitle": "5. Abstraction & Interfaces",
    "lessonNumber": "Lesson 5.3",
    "title": "Abstract Class vs Interface: When to Use Which?",
    "subtitle": "Architectural decision framework: IS-A core identity vs CAN-DO capability, state sharing, evolutionary compatibility, and mixin composition",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "default-and-static-interface-methods",
    "moduleId": "java-abstraction",
    "moduleTitle": "5. Abstraction & Interfaces",
    "lessonNumber": "Lesson 5.4",
    "title": "Java 8+ Default & Static Methods in Interfaces",
    "subtitle": "Interface evolution without breaking implementations, the default keyword, resolution rules for multiple inheritance conflicts, and utility static methods",
    "estimatedMinutes": 22,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "abstraction-challenge",
    "moduleId": "java-abstraction",
    "moduleTitle": "5. Abstraction & Interfaces",
    "lessonNumber": "Lesson 5.5",
    "title": "Module 5 Challenge & Interview Assessment",
    "subtitle": "Comprehensive assessment, real-world interview challenges, and capstone coding exercises combining all abstraction and interface pillars",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "object-root-class",
    "moduleId": "java-object-class",
    "moduleTitle": "6. Object Class & Contract",
    "lessonNumber": "Lesson 6.1",
    "title": "The Root java.lang.Object Class",
    "subtitle": "The universal ancestor, JVM type hierarchy, default inherited methods, and universal reference polymorphism",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "tostring-method-override",
    "moduleId": "java-object-class",
    "moduleTitle": "6. Object Class & Contract",
    "lessonNumber": "Lesson 6.2",
    "title": "The toString() Method & String Representation",
    "subtitle": "Deconstructing the default ClassName@hexHashCode format, string concatenation mechanics, logging readability, and builder patterns",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "equals-and-hashcode-contract",
    "moduleId": "java-object-class",
    "moduleTitle": "6. Object Class & Contract",
    "lessonNumber": "Lesson 6.3",
    "title": "The equals() and hashCode() Contract",
    "subtitle": "Identity vs value equality, the 5 mathematical properties of equals, hash collision mechanics, bucket distribution, and the unbreakable contract",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "shallow-vs-deep-copy",
    "moduleId": "java-object-class",
    "moduleTitle": "6. Object Class & Contract",
    "lessonNumber": "Lesson 6.4",
    "title": "Shallow Copy vs Deep Copy & Cloning",
    "subtitle": "Object duplication mechanics, Cloneable marker interface, field-by-field bitwise copy, deep recursive cloning, and copy constructors",
    "estimatedMinutes": 22,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "object-class-challenge",
    "moduleId": "java-object-class",
    "moduleTitle": "6. Object Class & Contract",
    "lessonNumber": "Lesson 6.5",
    "title": "Module 6 Challenge & Interview Assessment",
    "subtitle": "Comprehensive assessment, real-world interview challenges, and capstone coding exercises combining all Object class methods and contracts",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "java-records",
    "moduleId": "java-oop-misc",
    "moduleTitle": "7. Modern OOP & Miscellaneous Concepts",
    "lessonNumber": "Lesson 7.1",
    "title": "Java Records (record): Modern Immutability & Rep-Leaks",
    "subtitle": "Immutable data carriers, compact & canonical constructors, accessor semantics, and defensive copying",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "sealed-classes-interfaces",
    "moduleId": "java-oop-misc",
    "moduleTitle": "7. Modern OOP & Miscellaneous Concepts",
    "lessonNumber": "Lesson 7.2",
    "title": "Sealed Classes & Interfaces: Constrained Hierarchies & Pattern Matching",
    "subtitle": "Bounded type hierarchies, permits clause, exhaustive pattern matching, and sum types",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "nested-inner-classes",
    "moduleId": "java-oop-misc",
    "moduleTitle": "7. Modern OOP & Miscellaneous Concepts",
    "lessonNumber": "Lesson 7.3",
    "title": "Nested & Inner Classes: Static vs Non-Static & The Memory Leak Trap",
    "subtitle": "Static nested vs non-static inner classes, Outer.this reference, memory leaks, and local class capture",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "liskov-substitution-principle",
    "moduleId": "java-oop-misc",
    "moduleTitle": "7. Modern OOP & Miscellaneous Concepts",
    "lessonNumber": "Lesson 7.4",
    "title": "Liskov Substitution Principle (LSP) & Hierarchy Pitfalls",
    "subtitle": "Behavioral subtyping, precondition & postcondition rules, exception covariance, and Square-Rectangle anti-pattern",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 15,
    "interviewCount": 11
  },
  {
    "id": "oop-misc-challenge",
    "moduleId": "java-oop-misc",
    "moduleTitle": "7. Modern OOP & Miscellaneous Concepts",
    "lessonNumber": "Lesson 7.5",
    "title": "Module 7 Challenge & Modern OOP Assessment",
    "subtitle": "Comprehensive assessment, code puzzles, and interview evaluation covering Java Records, Sealed Hierarchies, Inner Classes, and Liskov Substitution",
    "estimatedMinutes": 25,
    "exerciseCount": 11,
    "quizCount": 15,
    "interviewCount": 12
  },
  {
    "id": "big-o-asymptotic-analysis",
    "moduleId": "java-dsa-foundations",
    "moduleTitle": "15. DSA Foundations & Searching",
    "lessonNumber": "Lesson 15.1",
    "title": "Big-O Asymptotic Analysis & Space Complexity",
    "subtitle": "Deconstructing upper bounds ($O$), lower bounds ($\\Omega$), tight bounds ($\\Theta$), auxiliary memory, call stack frame growth, and amortized complexity in Java data structures",
    "estimatedMinutes": 20,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "linear-search-and-sentinels",
    "moduleId": "java-dsa-foundations",
    "moduleTitle": "15. DSA Foundations & Searching",
    "lessonNumber": "Lesson 15.2",
    "title": "Linear Search, Sentinels & Early Termination",
    "subtitle": "Sequential array inspection, early termination invariants, sentinel search branch reduction, two-pass collection, and multi-dimensional matrix scanning",
    "estimatedMinutes": 18,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "binary-search-bounds-and-invariants",
    "moduleId": "java-dsa-foundations",
    "moduleTitle": "15. DSA Foundations & Searching",
    "lessonNumber": "Lesson 15.3",
    "title": "Binary Search: Midpoint Overflow, Bounds & Invariants",
    "subtitle": "Divide-and-conquer interval halving, the classic integer overflow bug, lower bound vs upper bound, search space reduction, and Arrays.binarySearch semantics",
    "estimatedMinutes": 22,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "merge-quick-timsort-internals",
    "moduleId": "java-dsa-foundations",
    "moduleTitle": "15. DSA Foundations & Searching",
    "lessonNumber": "Lesson 15.4",
    "title": "Divide-and-Conquer Sorting: Merge Sort vs Quick Sort vs TimSort",
    "subtitle": "Recursive decomposition, Merge Sort stability and $O(N)$ auxiliary buffers, QuickSort partitioning schemes, Dual-Pivot Quicksort, and Java's TimSort hybrid engine",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "stack-adt-and-arraydeque",
    "moduleId": "java-dsa-stacks-queues",
    "moduleTitle": "16. Stacks, Queues & Lists",
    "lessonNumber": "Lesson 16.1",
    "title": "Stack Architecture & ArrayDeque Implementation",
    "subtitle": "LIFO operational semantics, push/pop/peek mechanics, why java.util.Stack is legacy, ArrayDeque cache performance, Monotonic Stack pattern, and expression parsing",
    "estimatedMinutes": 22,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "queue-adt-and-ring-buffers",
    "moduleId": "java-dsa-stacks-queues",
    "moduleTitle": "16. Stacks, Queues & Lists",
    "lessonNumber": "Lesson 16.2",
    "title": "Queue Architecture, FIFO Ring Buffers & Priority Queues",
    "subtitle": "FIFO operational invariants, circular array modulo wrapping, offer/poll/peek vs add/remove/element exceptions, and PriorityQueue min-heap internals",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "singly-doubly-linked-lists",
    "moduleId": "java-dsa-stacks-queues",
    "moduleTitle": "16. Stacks, Queues & Lists",
    "lessonNumber": "Lesson 16.3",
    "title": "Singly & Doubly Linked List Internals",
    "subtitle": "Node object heap layout, reference pointer manipulation, sentinel dummy nodes, in-place pointer reversal ($O(1)$ space), and linked list vs dynamic array cache performance",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "floyd-cycle-detection-and-pointers",
    "moduleId": "java-dsa-stacks-queues",
    "moduleTitle": "16. Stacks, Queues & Lists",
    "lessonNumber": "Lesson 16.4",
    "title": "Fast-Slow Pointers & Floyd's Cycle Detection",
    "subtitle": "Tortoise and Hare algorithm, cycle existence detection, mathematical proof of cycle entrance node ($F = kC - a$), single-pass midpoint location, and in-place palindrome verification",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "two-pointers-converging",
    "moduleId": "java-dsa-patterns",
    "moduleTitle": "17. Two Pointers & Sliding Window",
    "lessonNumber": "Lesson 17.1",
    "title": "Two Pointers: Converging Left-Right Pointers",
    "subtitle": "Opposite-direction pointer convergence, monotonic search space elimination, Two Sum II, Container With Most Water, 3Sum reduction, and Trapping Rain Water",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "fast-slow-pointer-traversal",
    "moduleId": "java-dsa-patterns",
    "moduleTitle": "17. Two Pointers & Sliding Window",
    "lessonNumber": "Lesson 17.2",
    "title": "Fast & Slow Pointer Traversal",
    "subtitle": "Same-direction pointer traversal, in-place array modification, duplicate removal invariants, zero partitioning, Floyd's cycle detection on arrays, and Happy Number",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "fixed-size-sliding-window",
    "moduleId": "java-dsa-patterns",
    "moduleTitle": "17. Two Pointers & Sliding Window",
    "lessonNumber": "Lesson 17.3",
    "title": "Sliding Window: Fixed Size Subarrays",
    "subtitle": "Constant window width $K$, running state maintenance in $O(1)$, Max Sum Subarray, Anagram detection, Monotonic Deque for Sliding Window Maximum, and numeric overflow guards",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "dynamic-sliding-window",
    "moduleId": "java-dsa-patterns",
    "moduleTitle": "17. Two Pointers & Sliding Window",
    "lessonNumber": "Lesson 17.4",
    "title": "Sliding Window: Dynamic Window & Invariants",
    "subtitle": "Variable-size sliding window, expansion and contraction invariants, Longest Substring Without Repeating Characters, Minimum Window Substring, and exact-K decomposition",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "collections-framework-overview",
    "moduleId": "java-collections",
    "moduleTitle": "18. Collections Framework",
    "lessonNumber": "Lesson 18.1",
    "title": "Collections Framework Architecture & Fail-Fast Iterators",
    "subtitle": "Iterable and Collection hierarchies, List/Set/Queue contracts, fail-fast vs fail-safe iterators, modCount mutation tracking, and ConcurrentModificationException",
    "estimatedMinutes": 24,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "arraylist-vs-linkedlist-internals",
    "moduleId": "java-collections",
    "moduleTitle": "18. Collections Framework",
    "lessonNumber": "Lesson 18.2",
    "title": "ArrayList vs LinkedList Under the Hood",
    "subtitle": "Dynamic resizing factor, elementData array, System.arraycopy, LinkedList doubly-linked Node overhead, CPU cache line locality, and Big-O benchmarks",
    "estimatedMinutes": 26,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "set-hierarchy-and-treeset",
    "moduleId": "java-collections",
    "moduleTitle": "18. Collections Framework",
    "lessonNumber": "Lesson 18.3",
    "title": "Set Hierarchy: HashSet, LinkedHashSet & TreeSet",
    "subtitle": "HashSet backing HashMap, dummy PRESENT Object, LinkedHashSet doubly-linked iteration, TreeSet Red-Black tree navigation, and compareTo vs equals contract",
    "estimatedMinutes": 26,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "queue-deque-and-priorityqueue",
    "moduleId": "java-collections",
    "moduleTitle": "18. Collections Framework",
    "lessonNumber": "Lesson 18.4",
    "title": "Queue, Deque & PriorityQueue Internals",
    "subtitle": "FIFO Queue contracts, ArrayDeque circular ring-buffer, PriorityQueue binary min-heap array representation, siftUp/siftDown algorithms, and thread-safe queues",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "hashmap-internal-architecture",
    "moduleId": "java-hashing",
    "moduleTitle": "19. Hashing & HashMap Internals",
    "lessonNumber": "Lesson 19.1",
    "title": "HashMap Architecture: Buckets, Node<K,V>, and Hash Spreading",
    "subtitle": "Node<K,V>[] table, hash perturbation function, power-of-two bitwise indexing, lazy table allocation, and putVal execution flow",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "hash-collisions-and-treeification",
    "moduleId": "java-hashing",
    "moduleTitle": "19. Hashing & HashMap Internals",
    "lessonNumber": "Lesson 19.2",
    "title": "Hash Collisions, Chaining & Red-Black Treeification",
    "subtitle": "Separate chaining, TREEIFY_THRESHOLD = 8, UNTREEIFY_THRESHOLD = 6, MIN_TREEIFY_CAPACITY = 64, TreeNode conversion, and Comparable tie-breaking",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "hashmap-resizing-and-rehash",
    "moduleId": "java-hashing",
    "moduleTitle": "19. Hashing & HashMap Internals",
    "lessonNumber": "Lesson 19.3",
    "title": "HashMap Resizing, Load Factor & Rehashing Mechanics",
    "subtitle": "DEFAULT_LOAD_FACTOR = 0.75f, threshold calculation, doubling capacity, bit-test split (e.hash & oldCap) == 0, and the Java 7 infinite loop race condition",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "concurrenthashmap-internals",
    "moduleId": "java-hashing",
    "moduleTitle": "19. Hashing & HashMap Internals",
    "lessonNumber": "Lesson 19.4",
    "title": "ConcurrentHashMap: CAS, Synchronized Buckets & Lock-Free Reads",
    "subtitle": "Java 7 Segment striping vs Java 8 CAS & synchronized bucket heads, volatile memory visibility, multi-threaded transfer, and lock-free reads",
    "estimatedMinutes": 30,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "generic-types-and-methods",
    "moduleId": "java-generics",
    "moduleTitle": "20. Generics & Type Safety",
    "lessonNumber": "Lesson 20.1",
    "title": "Generic Types, Classes & Methods",
    "subtitle": "Parameterized types, type parameters <T>, multi-type classes Pair<K,V>, generic methods, and compile-time type safety vs raw types",
    "estimatedMinutes": 26,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "type-erasure-and-bridge-methods",
    "moduleId": "java-generics",
    "moduleTitle": "20. Generics & Type Safety",
    "lessonNumber": "Lesson 20.2",
    "title": "Type Erasure & Synthetic Bridge Methods",
    "subtitle": "Compile-time type erasure, erasure to Object or upper bound, synthetic bridge methods in bytecode, checkcast instructions, and reflection inspection",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "wildcards-and-pecs-principle",
    "moduleId": "java-generics",
    "moduleTitle": "20. Generics & Type Safety",
    "lessonNumber": "Lesson 20.3",
    "title": "Wildcards & The PECS Principle (Producer Extends, Consumer Super)",
    "subtitle": "Generic invariance, unbounded wildcards (<?>), upper bounds (<? extends T>), lower bounds (<? super T>), and Joshua Bloch`s PECS mnemonic",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "generics-limitations-and-heap-pollution",
    "moduleId": "java-generics",
    "moduleTitle": "20. Generics & Type Safety",
    "lessonNumber": "Lesson 20.4",
    "title": "Generics Limitations, Arrays & Heap Pollution",
    "subtitle": "Primitive types restriction, inability to instantiate new T(), non-reifiable types, generic array creation ban, heap pollution, and @SafeVarargs",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "throwable-hierarchy-checked-unchecked",
    "moduleId": "java-exceptions",
    "moduleTitle": "21. Exception Handling",
    "lessonNumber": "Lesson 21.1",
    "title": "Throwable Hierarchy, Error vs Exception & Checked vs Unchecked",
    "subtitle": "java.lang.Throwable root, Error vs Exception, RuntimeException unchecked hierarchy, compile-time verified checked exceptions, throws signature, and overriding rules",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "try-catch-finally-execution-order",
    "moduleId": "java-exceptions",
    "moduleTitle": "21. Exception Handling",
    "lessonNumber": "Lesson 21.2",
    "title": "try-catch-finally Semantics, Multi-Catch & Execution Order Traps",
    "subtitle": "Exception propagation up the call stack, catch ordering inheritance rules, Java 7 multi-catch disjoint types, finally guarantees, System.exit scenarios, and the return-in-finally trap",
    "estimatedMinutes": 26,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "try-with-resources-autocloseable",
    "moduleId": "java-exceptions",
    "moduleTitle": "21. Exception Handling",
    "lessonNumber": "Lesson 21.3",
    "title": "try-with-resources, AutoCloseable & Suppressed Exceptions",
    "subtitle": "Resource leak hazards in pre-Java 7 finally blocks, java.lang.AutoCloseable vs java.io.Closeable, reverse closure ordering, effectively final resources in Java 9+, and Throwable.getSuppressed() mechanics",
    "estimatedMinutes": 28,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "custom-exceptions-best-practices",
    "moduleId": "java-exceptions",
    "moduleTitle": "21. Exception Handling",
    "lessonNumber": "Lesson 21.4",
    "title": "Custom Exceptions, Chaining & Anti-Patterns",
    "subtitle": "Domain-specific exceptions, extending RuntimeException vs Exception, constructor overloads, exception chaining with initCause/getCause, stack trace preservation, and the 7 deadly anti-patterns",
    "estimatedMinutes": 26,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "lambdas-and-functional-interfaces",
    "moduleId": "java-streams",
    "moduleTitle": "22. Java 8+ Streams & Lambdas",
    "lessonNumber": "Lesson 22.1",
    "title": "Lambdas, Functional Interfaces & Method References",
    "subtitle": "@FunctionalInterface SAM contract, java.util.function primitives & compositions, invokedynamic bytecode mechanics, method references (4 types), and effectively final closures",
    "estimatedMinutes": 30,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "stream-pipeline-intermediate-operations",
    "moduleId": "java-streams",
    "moduleTitle": "22. Java 8+ Streams & Lambdas",
    "lessonNumber": "Lesson 22.2",
    "title": "Stream Pipeline Lifecycle & Intermediate Operations",
    "subtitle": "Declarative pipelines, lazy evaluation, stateless vs stateful operations, short-circuiting mechanics, stream consumption rule, and primitive streams",
    "estimatedMinutes": 30,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "terminal-operations-and-collectors",
    "moduleId": "java-streams",
    "moduleTitle": "22. Java 8+ Streams & Lambdas",
    "lessonNumber": "Lesson 22.3",
    "title": "Terminal Operations, Reduction & Advanced Collectors",
    "subtitle": "Eager pipeline execution, reduce() accumulator vs combiner, Collectors.toList/toSet/toMap collision handling, groupingBy multi-level aggregation, partitioningBy, and custom Collector mechanics",
    "estimatedMinutes": 32,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  },
  {
    "id": "optional-and-parallel-streams",
    "moduleId": "java-streams",
    "moduleTitle": "22. Java 8+ Streams & Lambdas",
    "lessonNumber": "Lesson 22.4",
    "title": "Optional<T> Best Practices & Parallel Streams",
    "subtitle": "Null-safety return mechanics, orElse() eager evaluation trap vs orElseGet(), monadic chaining (map/flatMap/filter), ForkJoinPool.commonPool(), Spliterator splitting overhead, and stateful race conditions",
    "estimatedMinutes": 32,
    "exerciseCount": 10,
    "quizCount": 10,
    "interviewCount": 10
  }
];

export function getSublessonSummariesForModule(moduleId: string): SubLessonSummary[] {
  if (!moduleId) return [];
  const clean = moduleId.trim().toLowerCase();
  return SUBLESSON_MANIFEST.filter(
    s => s.moduleId === clean || s.moduleId.toLowerCase() === clean
  );
}

export function getSublessonSummary(id: string): SubLessonSummary | undefined {
  if (!id) return undefined;
  const clean = id.trim().toLowerCase();
  return SUBLESSON_MANIFEST.find(s => s.id === clean || s.id.toLowerCase() === clean);
}

export function getAllSublessonSummaries(): SubLessonSummary[] {
  return SUBLESSON_MANIFEST;
}
