import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { BookOpen, Lightbulb, Code, AlertTriangle, Target, RefreshCw, CheckCircle, ChevronDown, ChevronRight, ArrowLeft } from 'lucide-react';
import { JAVA_MODULES } from '../../data/java/curriculum';
import { getJavaProgress, markLessonComplete } from '../../utils/javaStorage';

const INLINE_LESSON_DATA: Record<string, any> = {
  'java-fundamentals': {
    keyConcepts: [
      { term: 'JVM', definition: 'Java Virtual Machine - executes Java bytecode' },
      { term: 'JRE', definition: 'Java Runtime Environment - contains JVM and libraries' },
      { term: 'JDK', definition: 'Java Development Kit - contains JRE and development tools' },
      { term: 'Bytecode', definition: 'Platform-independent code generated by Java compiler' }
    ],
    codeExamples: [
      { code: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello World");\n  }\n}', output: 'Hello World' },
      { code: 'int x = 10;\nSystem.out.println("Value: " + x);', output: 'Value: 10' }
    ],
    commonMistakes: [
      'Forgetting the public static void main signature',
      'Confusing JDK, JRE, and JVM',
      'Missing semicolons at the end of statements'
    ],
    interviewTips: [
      'Be able to explain the "Write Once, Run Anywhere" principle',
      'Understand the compilation and execution flow'
    ],
    revisionPoints: [
      'Java is platform-independent at runtime',
      'Execution starts from main method',
      'File name must match public class name',
      'Case-sensitive language'
    ]
  },
  'java-data-types': {
    keyConcepts: [
      { term: 'Primitive Types', definition: 'Basic data types like int, char, boolean, double' },
      { term: 'Reference Types', definition: 'Objects, Arrays, and Strings' },
      { term: 'Type Casting', definition: 'Converting one primitive data type into another' },
      { term: 'Wrapper Classes', definition: 'Object representations of primitive types (e.g., Integer for int)' }
    ],
    codeExamples: [
      { code: 'int num = 10;\ndouble d = num; // Implicit casting\nSystem.out.println(d);', output: '10.0' },
      { code: 'double d = 10.5;\nint num = (int) d; // Explicit casting\nSystem.out.println(num);', output: '10' }
    ],
    commonMistakes: [
      'Integer overflow (e.g., adding to Integer.MAX_VALUE)',
      'Comparing floats/doubles using == instead of a tolerance',
      'NullPointerException when unboxing null wrapper class'
    ],
    interviewTips: [
      'Know the default values and sizes of primitives',
      'Understand when to use wrappers vs primitives'
    ],
    revisionPoints: [
      '8 primitive types in Java',
      'String is immutable and a reference type',
      'Autoboxing and unboxing in Java 5+'
    ]
  },
  'java-strings': {
    keyConcepts: [
      { term: 'Immutability', definition: 'String objects cannot be changed once created' },
      { term: 'String Pool', definition: 'Special memory region in heap for storing literal strings' },
      { term: 'StringBuilder', definition: 'Mutable sequence of characters (not thread-safe)' },
      { term: 'StringBuffer', definition: 'Mutable sequence of characters (thread-safe)' }
    ],
    codeExamples: [
      { code: 'String s1 = "Hello";\nString s2 = "Hello";\nSystem.out.println(s1 == s2);', output: 'true' },
      { code: 'String s3 = new String("Hello");\nSystem.out.println(s1 == s3);\nSystem.out.println(s1.equals(s3));', output: 'false\ntrue' }
    ],
    commonMistakes: [
      'Using == instead of .equals() for string comparison',
      'Concatenating strings in a loop using + (use StringBuilder instead)',
      'Assuming String methods modify the original string'
    ],
    interviewTips: [
      'Always use .equals() for value comparison',
      'Understand how the String pool works to save memory',
      'Know when to use StringBuilder over String'
    ],
    revisionPoints: [
      'String is final and immutable',
      '+ operator is overloaded for String concatenation',
      'StringBuilder is faster than StringBuffer'
    ]
  },
  'java-oop-basics': {
    keyConcepts: [
      { term: 'Class & Object', definition: 'Blueprint vs Instance' },
      { term: 'Encapsulation', definition: 'Hiding internal state and requiring all interaction through methods' },
      { term: 'Constructors', definition: 'Special method invoked when an object is created' },
      { term: 'this Keyword', definition: 'Reference to the current object' }
    ],
    codeExamples: [
      { code: 'class Person {\n  private String name;\n  public Person(String n) { this.name = n; }\n  public String getName() { return name; }\n}\nPerson p = new Person("Alice");\nSystem.out.println(p.getName());', output: 'Alice' }
    ],
    commonMistakes: [
      'Making fields public instead of private',
      'Forgetting to provide a no-arg constructor when defining custom constructors',
      'Misunderstanding pass-by-value semantics for object references'
    ],
    interviewTips: [
      'Be ready to design a simple class modeling a real-world object',
      'Explain the pillars of OOP (Encapsulation, Abstraction, Inheritance, Polymorphism)'
    ],
    revisionPoints: [
      'Java uses pass-by-value for both primitives and object references',
      'Constructors do not have a return type',
      'Access modifiers: private, default, protected, public'
    ]
  },
  'java-inheritance': {
    keyConcepts: [
      { term: 'Inheritance', definition: 'Mechanism where one class acquires the properties of another' },
      { term: 'Polymorphism', definition: 'Ability of an object to take on many forms' },
      { term: 'Method Overriding', definition: 'Subclass provides a specific implementation of a method' },
      { term: 'super Keyword', definition: 'Reference variable used to refer to immediate parent class object' }
    ],
    codeExamples: [
      { code: 'class Animal {\n  void makeSound() { System.out.println("Some sound"); }\n}\nclass Dog extends Animal {\n  @Override\n  void makeSound() { System.out.println("Bark"); }\n}\nAnimal a = new Dog();\na.makeSound();', output: 'Bark' }
    ],
    commonMistakes: [
      'Trying to inherit multiple classes (Java doesn\'t support multiple class inheritance)',
      'Forgetting the @Override annotation',
      'Confusing Overloading (compile-time) and Overriding (runtime)'
    ],
    interviewTips: [
      'Explain IS-A vs HAS-A relationships',
      'Understand how constructors work in an inheritance hierarchy'
    ],
    revisionPoints: [
      'Every class inherits from Object implicitly',
      'Constructors are not inherited',
      'Dynamic method dispatch resolves overridden methods at runtime'
    ]
  }
};

const Section = ({ title, icon: Icon, children, defaultOpen = false }: { title: string, icon: any, children: React.ReactNode, defaultOpen?: boolean }) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  return (
    <div className="bg-slate-800 rounded-lg border border-slate-700 overflow-hidden mb-4">
      <button 
        className="w-full flex items-center justify-between p-4 bg-slate-800 hover:bg-slate-700 transition-colors"
        onClick={() => setIsOpen(!isOpen)}
      >
        <div className="flex items-center gap-3">
          <Icon className="text-blue-400 w-5 h-5" />
          <h2 className="text-xl font-bold text-slate-100">{title}</h2>
        </div>
        {isOpen ? <ChevronDown className="text-slate-400" /> : <ChevronRight className="text-slate-400" />}
      </button>
      {isOpen && <div className="p-4 border-t border-slate-700">{children}</div>}
    </div>
  );
};

const JavaModulePage: React.FC = () => {
  const { moduleId } = useParams<{ moduleId: string }>();
  const [isCompleted, setIsCompleted] = useState(false);
  
  const module = JAVA_MODULES.find(m => m.id === moduleId);
  const lessonData = INLINE_LESSON_DATA[moduleId || ''] || null;

  useEffect(() => {
    if (moduleId) {
      const progress = getJavaProgress();
      if (progress.lessonsCompleted.includes(moduleId)) {
        setIsCompleted(true);
      }
    }
  }, [moduleId]);

  const handleMarkComplete = () => {
    if (moduleId) {
      markLessonComplete(moduleId);
      setIsCompleted(true);
    }
  };

  if (!module) {
    return <div className="p-8 text-center text-slate-300">Module not found.</div>;
  }

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 p-6">
      <div className="max-w-4xl mx-auto">
        <Link to="/java" className="inline-flex items-center text-blue-400 hover:text-blue-300 mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Java Dashboard
        </Link>
        
        <header className="mb-8 bg-slate-800 p-6 rounded-xl border border-slate-700">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold mb-2 text-white">{module.title}</h1>
              <div className="flex items-center gap-4 text-sm text-slate-400">
                <span className="bg-slate-700 px-3 py-1 rounded-full">{module.difficulty}</span>
                <span>{module.estimatedMinutes} mins</span>
              </div>
            </div>
            {isCompleted && (
              <span className="flex items-center text-green-400 bg-green-400/10 px-4 py-2 rounded-lg">
                <CheckCircle className="w-5 h-5 mr-2" />
                Completed
              </span>
            )}
          </div>
          <p className="mt-4 text-slate-300">{module.description}</p>
        </header>

        <Section title="What You Will Learn" icon={BookOpen} defaultOpen={true}>
          <ul className="list-disc list-inside space-y-2 text-slate-300">
            {module.topics.map((topic, i) => (
              <li key={i}>{topic}</li>
            ))}
          </ul>
        </Section>

        {lessonData ? (
          <>
            <Section title="Key Concepts" icon={Lightbulb} defaultOpen={true}>
              <div className="grid gap-4 md:grid-cols-2">
                {lessonData.keyConcepts.map((concept: any, i: number) => (
                  <div key={i} className="bg-slate-900 p-4 rounded-lg border border-slate-700">
                    <h3 className="font-bold text-blue-400 mb-2">{concept.term}</h3>
                    <p className="text-sm text-slate-300">{concept.definition}</p>
                  </div>
                ))}
              </div>
            </Section>

            <Section title="Code Examples" icon={Code}>
              <div className="space-y-4">
                {lessonData.codeExamples.map((ex: any, i: number) => (
                  <div key={i} className="bg-slate-950 rounded-lg overflow-hidden border border-slate-800">
                    <div className="bg-slate-800 px-4 py-2 text-xs font-mono text-slate-400">Example {i + 1}</div>
                    <pre className="p-4 text-sm text-green-400 overflow-x-auto"><code>{ex.code}</code></pre>
                    <div className="bg-slate-900 border-t border-slate-800 p-3">
                      <span className="text-xs text-slate-500 uppercase font-bold tracking-wider">Output:</span>
                      <pre className="text-slate-300 text-sm mt-1">{ex.output}</pre>
                    </div>
                  </div>
                ))}
              </div>
            </Section>

            <Section title="Common Mistakes" icon={AlertTriangle}>
              <ul className="list-disc list-inside space-y-2 text-slate-300">
                {lessonData.commonMistakes.map((mistake: string, i: number) => (
                  <li key={i}>{mistake}</li>
                ))}
              </ul>
            </Section>

            <Section title="Interview Tips" icon={Target}>
              <ul className="list-disc list-inside space-y-2 text-slate-300">
                {lessonData.interviewTips.map((tip: string, i: number) => (
                  <li key={i}>{tip}</li>
                ))}
              </ul>
            </Section>

            <Section title="Revision Points" icon={RefreshCw}>
              <ul className="list-disc list-inside space-y-2 text-slate-300">
                {lessonData.revisionPoints.map((point: string, i: number) => (
                  <li key={i}>{point}</li>
                ))}
              </ul>
            </Section>
          </>
        ) : (
          <div className="bg-slate-800 p-6 rounded-lg border border-slate-700 text-center">
            <p className="text-slate-400">Detailed lesson content for this module will be available soon.</p>
          </div>
        )}

        <div className="mt-8 flex flex-wrap gap-4 border-t border-slate-800 pt-8 pb-12">
          {!isCompleted && (
            <button
              onClick={handleMarkComplete}
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-lg font-semibold transition-colors"
            >
              <CheckCircle className="w-5 h-5" />
              Mark as Learned
            </button>
          )}
          <Link
            to={`/java/mcq/${moduleId}`}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-3 rounded-lg font-semibold transition-colors"
          >
            Practice MCQs
          </Link>
          <Link
            to="/java/mock-interview"
            className="flex items-center gap-2 bg-slate-700 hover:bg-slate-600 text-white px-6 py-3 rounded-lg font-semibold transition-colors"
          >
            Mock Interview
          </Link>
        </div>
      </div>
    </div>
  );
};

export default JavaModulePage;

