export interface JavaMCQ {
  id: string;
  moduleId: string;
  question: string;
  code?: string;
  options: string[];
  correctAnswer: number; // 0-indexed
  explanation: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  type: 'conceptual' | 'output' | 'debugging' | 'syntax';
  tags: string[];
}

export const javaFundamentalsQuestions: JavaMCQ[] = [
  {
    id: "fundamentals-1",
    moduleId: "java-fundamentals",
    question: "Which of the following components is responsible for providing the runtime environment and executing Java bytecode?",
    options: [
      "JDK (Java Development Kit)",
      "JVM (Java Virtual Machine)",
      "JRE (Java Runtime Environment)",
      "JIT (Just-In-Time Compiler)"
    ],
    correctAnswer: 2,
    explanation: "The JRE (Java Runtime Environment) provides the libraries, the Java Virtual Machine, and other components to run applets and applications written in the Java programming language. JVM is a part of JRE, but JRE is the complete runtime environment.",
    difficulty: "Easy",
    type: "conceptual",
    tags: ["architecture", "jvm", "jre"]
  },
  {
    id: "fundamentals-2",
    moduleId: "java-fundamentals",
    question: "What is the primary output generated by the 'javac' compiler?",
    options: [
      "Machine code specific to the operating system",
      "Assembly code",
      "Bytecode stored in a .class file",
      "An executable .exe file"
    ],
    correctAnswer: 2,
    explanation: "The Java compiler (javac) translates Java source code (.java) into platform-independent bytecode, which is stored in a .class file.",
    difficulty: "Easy",
    type: "conceptual",
    tags: ["compilation", "javac"]
  },
  {
    id: "fundamentals-3",
    moduleId: "java-fundamentals",
    question: "What is Java bytecode?",
    options: [
      "Source code written in Java",
      "Machine code for a specific CPU architecture",
      "An intermediate language that is executed by the JVM",
      "A script that runs directly in a web browser"
    ],
    correctAnswer: 2,
    explanation: "Bytecode is a highly optimized set of instructions designed to be executed by the Java Virtual Machine (JVM), rather than directly by the computer's CPU.",
    difficulty: "Easy",
    type: "conceptual",
    tags: ["bytecode", "jvm"]
  },
  {
    id: "fundamentals-4",
    moduleId: "java-fundamentals",
    question: "Which feature makes Java platform-independent?",
    options: [
      "It can be compiled to native machine code on any operating system",
      "Java source code is interpreted directly by the OS",
      "The use of a JVM to translate bytecode to machine code at runtime",
      "Java programs do not interact with the operating system"
    ],
    correctAnswer: 2,
    explanation: "Java's platform independence ('Write Once, Run Anywhere') is achieved because the compiler generates bytecode, which is then interpreted or compiled at runtime by a platform-specific JVM.",
    difficulty: "Medium",
    type: "conceptual",
    tags: ["platform-independence", "jvm"]
  },
  {
    id: "fundamentals-5",
    moduleId: "java-fundamentals",
    question: "Which of the following is the standard entry point for a standalone Java application?",
    options: [
      "public void main(String[] args)",
      "public static void main(String[] args)",
      "static void main(String args[])",
      "public static int main(String[] args)"
    ],
    correctAnswer: 1,
    explanation: "The JVM looks for a specifically signed method: public static void main(String[] args) to begin execution.",
    difficulty: "Easy",
    type: "syntax",
    tags: ["main-method", "entry-point"]
  },
  {
    id: "fundamentals-6",
    moduleId: "java-fundamentals",
    question: "What is the purpose of the CLASSPATH environment variable?",
    options: [
      "To tell the operating system where the javac compiler is located",
      "To specify where the JVM and compiler should look for user-defined classes and packages",
      "To limit the amount of memory the JVM can use",
      "To define the location of the Java standard library only"
    ],
    correctAnswer: 1,
    explanation: "CLASSPATH is an environment variable used by the Java compiler and JVM to find user-defined classes and packages during compilation and execution.",
    difficulty: "Medium",
    type: "conceptual",
    tags: ["classpath", "environment"]
  },
  {
    id: "fundamentals-7",
    moduleId: "java-fundamentals",
    question: "What is the primary purpose of packages in Java?",
    options: [
      "To increase the execution speed of the program",
      "To convert Java source code to machine code",
      "To group related classes, avoid name conflicts, and control access",
      "To store primitive data types"
    ],
    correctAnswer: 2,
    explanation: "Packages are used in Java to prevent naming conflicts, control access levels, and organize related classes and interfaces logically.",
    difficulty: "Easy",
    type: "conceptual",
    tags: ["packages", "organization"]
  },
  {
    id: "fundamentals-8",
    moduleId: "java-fundamentals",
    question: "What happens when you use an import statement like 'import java.util.*;'?",
    options: [
      "All classes in the java.util package are loaded into memory immediately at startup.",
      "The compiler includes all source code from java.util into your class.",
      "It allows you to use simple class names from the java.util package without fully qualifying them.",
      "It automatically imports all sub-packages of java.util as well."
    ],
    correctAnswer: 2,
    explanation: "The import statement simply tells the compiler where to look for classes, allowing you to use simple names. It does not load classes into memory prematurely or import sub-packages.",
    difficulty: "Medium",
    type: "conceptual",
    tags: ["imports", "packages"]
  },
  {
    id: "fundamentals-9",
    moduleId: "java-fundamentals",
    question: "Which of the following is NOT a valid Java keyword?",
    options: [
      "volatile",
      "transient",
      "include",
      "strictfp"
    ],
    correctAnswer: 2,
    explanation: "'include' is used in languages like C/C++, but in Java, we use 'import'. The other options are valid Java keywords.",
    difficulty: "Easy",
    type: "syntax",
    tags: ["keywords", "syntax"]
  },
  {
    id: "fundamentals-10",
    moduleId: "java-fundamentals",
    question: "Which of the following is the correct syntax for a Javadoc comment?",
    options: [
      "/* This is a comment */",
      "// This is a comment",
      "/** This is a Javadoc comment */",
      "<!-- This is a comment -->"
    ],
    correctAnswer: 2,
    explanation: "Javadoc comments start with /** and end with */, and are used by the Javadoc tool to generate API documentation.",
    difficulty: "Easy",
    type: "syntax",
    tags: ["comments", "javadoc"]
  },
  {
    id: "fundamentals-11",
    moduleId: "java-fundamentals",
    question: "According to standard Java naming conventions, which of the following is the best name for a class representing an employee?",
    options: [
      "employee",
      "EmployeeRecord",
      "employee_record",
      "EMPLOYEERECORD"
    ],
    correctAnswer: 1,
    explanation: "In Java, class names should be nouns and start with an uppercase letter, following PascalCase (e.g., EmployeeRecord).",
    difficulty: "Easy",
    type: "conceptual",
    tags: ["naming-conventions", "best-practices"]
  },
  {
    id: "fundamentals-12",
    moduleId: "java-fundamentals",
    question: "Which of the following errors is typically caught at compile-time rather than run-time?",
    options: [
      "Trying to access an array element out of bounds",
      "Dividing an integer by zero",
      "Assigning a string literal to an integer variable",
      "Running out of memory (OutOfMemoryError)"
    ],
    correctAnswer: 2,
    explanation: "Type mismatch errors (like assigning a String to an int) are checked by the compiler (compile-time). The other errors occur during program execution (run-time).",
    difficulty: "Medium",
    type: "conceptual",
    tags: ["compile-time", "errors"]
  },
  {
    id: "fundamentals-13",
    moduleId: "java-fundamentals",
    question: "What will be the output of this program if run with the command: java Test Hello World",
    code: `public class Test {\n    public static void main(String[] args) {\n        System.out.println(args[0]);\n    }\n}`,
    options: [
      "Test",
      "Hello",
      "World",
      "ArrayIndexOutOfBoundsException"
    ],
    correctAnswer: 1,
    explanation: "The arguments passed to the main method start after the class name. args[0] refers to the first argument, which is 'Hello'.",
    difficulty: "Medium",
    type: "output",
    tags: ["main-method", "command-line", "arrays"]
  },
  {
    id: "fundamentals-14",
    moduleId: "java-fundamentals",
    question: "What is the output of the following code snippet?",
    code: `public class OutputTest {\n    public static void main(String[] args) {\n        System.out.print("Java ");\n        System.out.println("is ");\n        System.out.print("fun!");\n    }\n}`,
    options: [
      "Java is fun!",
      "Java \nis \nfun!",
      "Java is \nfun!",
      "Java\nis fun!"
    ],
    correctAnswer: 2,
    explanation: "System.out.print() prints without a newline. System.out.println() prints and then appends a newline. So 'Java ' and 'is ' are on one line, followed by a newline, and then 'fun!' is on the next line.",
    difficulty: "Easy",
    type: "output",
    tags: ["output", "console"]
  },
  {
    id: "fundamentals-15",
    moduleId: "java-fundamentals",
    question: "Assume this code is saved in a file named `App.java`. What happens when you try to compile and run it?",
    code: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("Started");\n    }\n}`,
    options: [
      "It compiles and prints 'Started'",
      "Compilation error: Class 'Main' is public, should be declared in a file named 'Main.java'",
      "Runtime error: ClassNotFoundException",
      "Compilation error: No public class 'App' found"
    ],
    correctAnswer: 1,
    explanation: "In Java, if a class is public, it must be defined in a file that exactly matches its name (i.e., Main.java). Since the file is App.java, compilation fails.",
    difficulty: "Medium",
    type: "syntax",
    tags: ["compilation", "file-naming"]
  },
  {
    id: "fundamentals-16",
    moduleId: "java-fundamentals",
    question: "Which of the following main method signatures is strictly valid and can act as the entry point for a Java application?",
    code: `1. public static void main(String[] args)\n2. static public void main(String[] args)\n3. public static void main(String... args)\n4. public void static main(String[] args)`,
    options: [
      "Only 1 is valid",
      "1 and 2 are valid",
      "1, 2, and 3 are valid",
      "All of them are valid"
    ],
    correctAnswer: 2,
    explanation: "Order of modifiers (public, static) doesn't matter, so 2 is valid. String... is varargs, which is treated as an array, making 3 valid. Option 4 is invalid because the return type (void) must come immediately before the method name.",
    difficulty: "Hard",
    type: "syntax",
    tags: ["main-method", "modifiers"]
  },
  {
    id: "fundamentals-17",
    moduleId: "java-fundamentals",
    question: "What is the output of the following code?",
    code: `public class StringTest {\n    public static void main(String[] args) {\n        System.out.println(10 + 20 + "Java" + 10 + 20);\n    }\n}`,
    options: [
      "1020Java1020",
      "30Java30",
      "30Java1020",
      "1020Java30"
    ],
    correctAnswer: 2,
    explanation: "Expression evaluation goes from left to right. 10 + 20 is evaluated as integer addition (30). Then 30 + 'Java' results in string concatenation ('30Java'). From that point, all subsequent + operations involve strings, so '30Java' + 10 becomes '30Java10', and then '30Java10' + 20 becomes '30Java1020'.",
    difficulty: "Medium",
    type: "output",
    tags: ["strings", "operators"]
  },
  {
    id: "fundamentals-18",
    moduleId: "java-fundamentals",
    question: "Will the following code compile?",
    code: `public class CommentTest {\n    public static void main(String[] args) {\n        /* This is a \n           /* nested */ \n           comment */\n        System.out.println("Hello");\n    }\n}`,
    options: [
      "Yes, it will print 'Hello'",
      "No, compilation error due to nested multi-line comments",
      "Yes, but it won't print anything",
      "No, runtime error"
    ],
    correctAnswer: 1,
    explanation: "Java does not support nested multi-line (block) comments. The first '*/' closes the comment, leaving the remaining 'comment */' as invalid syntax.",
    difficulty: "Easy",
    type: "syntax",
    tags: ["comments", "compilation"]
  },
  {
    id: "fundamentals-19",
    moduleId: "java-fundamentals",
    question: "You have compiled a class `com.app.Main` and the `.class` file is located at `/build/com/app/Main.class`. From the `/` directory, which command will execute it?",
    options: [
      "java build/com/app/Main",
      "java -cp build com.app.Main",
      "java -cp build/com/app Main",
      "java build.com.app.Main"
    ],
    correctAnswer: 1,
    explanation: "To run a class in a package, you must specify the root directory of the package hierarchy in the classpath (-cp), and then use the fully qualified class name. So you set classpath to 'build' and run 'com.app.Main'.",
    difficulty: "Hard",
    type: "debugging",
    tags: ["classpath", "packages", "execution"]
  },
  {
    id: "fundamentals-20",
    moduleId: "java-fundamentals",
    question: "What is the output of the following code?",
    code: `public class VariableTest {\n    public static void main(String[] args) {\n        int x;\n        if (args.length > 0) {\n            x = 10;\n        }\n        System.out.println(x);\n    }\n}`,
    options: [
      "10",
      "0",
      "Compilation error: variable x might not have been initialized",
      "Runtime error: NullPointerException"
    ],
    correctAnswer: 2,
    explanation: "Local variables in Java are not assigned default values. The compiler detects that 'x' might not be initialized if the if-condition is false, and therefore throws a compilation error.",
    difficulty: "Medium",
    type: "output",
    tags: ["variables", "compilation"]
  },
  {
    id: "fundamentals-21",
    moduleId: "java-fundamentals",
    question: "Which of the following statements about JDK, JRE, and JVM is TRUE?",
    options: [
      "JVM includes JRE and JDK.",
      "JDK includes JRE, which in turn includes JVM.",
      "JRE includes JDK, but requires a separate JVM.",
      "They are identical concepts just named differently based on OS."
    ],
    correctAnswer: 1,
    explanation: "The JDK (Java Development Kit) contains the tools for developing Java programs along with the JRE. The JRE (Java Runtime Environment) contains libraries and the JVM (Java Virtual Machine), which actually runs the bytecode.",
    difficulty: "Hard",
    type: "conceptual",
    tags: ["architecture", "jdk", "jre", "jvm"]
  },
  {
    id: "fundamentals-22",
    moduleId: "java-fundamentals",
    question: "How does the JIT (Just-In-Time) compiler interact with bytecode in modern JVMs?",
    options: [
      "It compiles Java source code directly into machine code.",
      "It translates bytecode into machine code right before execution to improve performance.",
      "It translates machine code back into bytecode for portability.",
      "It is an alternative to the javac compiler used during development."
    ],
    correctAnswer: 1,
    explanation: "The JIT compiler is part of the JVM. It compiles bytecode into native machine code at runtime (just-in-time) for frequently executed code blocks, significantly improving execution speed.",
    difficulty: "Hard",
    type: "conceptual",
    tags: ["jit", "jvm", "performance"]
  },
  {
    id: "fundamentals-23",
    moduleId: "java-fundamentals",
    question: "In Java, what happens if a class does not specify a package statement at the top of the file?",
    options: [
      "It will not compile.",
      "It is placed in the java.lang package by default.",
      "It is placed in an unnamed (default) package.",
      "It is automatically assigned to a package based on the folder name."
    ],
    correctAnswer: 2,
    explanation: "If no package is specified, the class is placed in the default, unnamed package. This is generally discouraged for non-trivial applications due to potential naming conflicts.",
    difficulty: "Medium",
    type: "conceptual",
    tags: ["packages", "defaults"]
  },
  {
    id: "fundamentals-24",
    moduleId: "java-fundamentals",
    question: "When declaring a constant variable in Java according to conventions, how should it be written?",
    options: [
      "Constant int maxUsers = 100;",
      "final int max_users = 100;",
      "static final int MAX_USERS = 100;",
      "const int MAX_USERS = 100;"
    ],
    correctAnswer: 2,
    explanation: "In Java, constants are declared using the 'static final' modifiers. The naming convention is to use ALL_CAPS with underscores separating words.",
    difficulty: "Medium",
    type: "syntax",
    tags: ["naming-conventions", "modifiers", "constants"]
  },
  {
    id: "fundamentals-25",
    moduleId: "java-fundamentals",
    question: "What is the output of the following code?",
    code: `public class TestLoop {\n    public static void main(String[] args) {\n        for(int i = 0; i < 5; i++) {\n            System.out.print(i + " ");\n        }\n        System.out.println(i);\n    }\n}`,
    options: [
      "0 1 2 3 4 5",
      "0 1 2 3 4 4",
      "Compilation error",
      "Runtime exception"
    ],
    correctAnswer: 2,
    explanation: "The variable 'i' is declared within the initialization block of the for-loop. Its scope is limited to the loop. Trying to access 'i' outside the loop results in a compilation error.",
    difficulty: "Hard",
    type: "output",
    tags: ["scope", "variables", "compilation"]
  }
];
